from data.data import Datos
import custom_exceptions

class DatosModulo(Datos):
    pass