from data.data import Datos
import custom_exceptions

class DatosDeposito(Datos):
    pass