from data.data import Datos
import custom_exceptions

class DatosPedido(Datos):
    pass