from data.data import Datos
import custom_exceptions

class DatosUsuario(Datos):
    pass